### PR TITLE
fix: use scoped logger if request.logger is not available

### LINKED ISSUE #84: Cannot read property 'info' of undefined
I have been getting this error whenever I refresh my Apollo graphql playground and based on the error trace `request.logger` inside `tryAddEvent` function (request completes ) is undefined
```log
TypeError: Cannot read property 'info' of undefined
    at Object.listener (/home/akumzy/momo/planner-server/node_modules/hapi-pino/index.js:120:25)
    at module.exports.internals.Podium.internals.Podium.emit (/home/akumzy/momo/planner-server/node_modules/@hapi/podium/lib/index.js:224:107)
    at Request._finalize (/home/akumzy/momo/planner-server/node_modules/@hapi/hapi/lib/request.js:447:27)
    at Request._reply (/home/akumzy/momo/planner-server/node_modules/@hapi/hapi/lib/request.js:391:14)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### PR DESCRIPTION
**Pull request by DiegoRBaquero**
Fixes #84

### CODE REVIEW

**Comment by mcollina** [comment]
please add a unit test
Il 5 feb 2020, 21:33 +0100, Coveralls <notifications@github.com>, ha scritto:

**Comment by DiegoRBaquero** [comment]
@mcollina Hey Matteo, thanks for the quick review, I have added a test to handle that case :)

File: index.js [hunk 1]
```diff
@@ -129,6 +129,9 @@ async function register (server, options) {
     }
 
     const info = request.info
+    const childBindings = getChildBindings(request)
+    request.logger = request.logger || logger.child(childBindings)
```
Comment (mcollina) [inline index.js]: Would you mind to put this in a if-block instead of using coditionals? I would like to avoid the assignment and calling `getChildBindings` if there is already a logger

Comment (DiegoRBaquero) [reply index.js]: Done!
